"""empty message

Revision ID: e62374d3e93c
Revises: 7bf9a4fd143d
Create Date: 2025-08-20 04:38:18.665858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e62374d3e93c'
down_revision = '7bf9a4fd143d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('item_type',
                              existing_type=postgresql.ENUM(
                                  'person', 'planet', name='favorite_type'),
                              type_=sa.String(length=10),
                              existing_nullable=False)

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('hair_color',
                              existing_type=sa.VARCHAR(length=30),
                              type_=sa.String(length=50),
                              existing_nullable=True)
        batch_op.alter_column('skin_color',
                              existing_type=sa.VARCHAR(length=30),
                              type_=sa.String(length=50),
                              existing_nullable=True)
        batch_op.alter_column('eye_color',
                              existing_type=sa.VARCHAR(length=30),
                              type_=sa.String(length=50),
                              existing_nullable=True)

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('gravity',
                              existing_type=sa.VARCHAR(length=30),
                              type_=sa.String(length=40),
                              existing_nullable=True)
        batch_op.alter_column('climate',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.String(length=120),
                              existing_nullable=True)
        batch_op.alter_column('terrain',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.String(length=120),
                              existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('terrain',
                              existing_type=sa.String(length=120),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=True)
        batch_op.alter_column('climate',
                              existing_type=sa.String(length=120),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=True)
        batch_op.alter_column('gravity',
                              existing_type=sa.String(length=40),
                              type_=sa.VARCHAR(length=30),
                              existing_nullable=True)

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('eye_color',
                              existing_type=sa.String(length=50),
                              type_=sa.VARCHAR(length=30),
                              existing_nullable=True)
        batch_op.alter_column('skin_color',
                              existing_type=sa.String(length=50),
                              type_=sa.VARCHAR(length=30),
                              existing_nullable=True)
        batch_op.alter_column('hair_color',
                              existing_type=sa.String(length=50),
                              type_=sa.VARCHAR(length=30),
                              existing_nullable=True)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('item_type',
                              existing_type=sa.String(length=10),
                              type_=postgresql.ENUM(
                                  'person', 'planet', name='favorite_type'),
                              existing_nullable=False)

    # ### end Alembic commands ###
